<?php

/**
 * Plugin Name: WooCommerce new account and lost password use users email in stead of username
 * Description: Default in new account and lost password emails is that the user gets information about its username. Autogenerated usernames are often useless. So, we replace the username with the users email which also can be used for logging in.  
 * Author:      Maksimer AS
 * Author URI:  https://www.maksimer.no/
 * Version:     1.0.0
 */
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

// Update checker
require 'plugin_update_check.php';
$MyUpdateChecker = new PluginUpdateChecker_2_0 (
    'https://kernl.us/api/v1/updates/5a07fda80c2ed85eb2f4e2e9/',
    __FILE__,
    'woocommerce-emails-use-email-not-username',
    48
);

add_filter( 'woocommerce_email_customer_new_account_user_login',       'maksimer_get_user_email_from_user_login', 10, 1 );
add_filter( 'woocommerce_email_customer_reset_password_user_login',    'maksimer_get_user_email_from_user_login', 10, 1 );

function maksimer_get_user_email_from_user_login( $user_login )    {
     
    $user = get_user_by( 'login', $user_login );
     
    if( $user )    {
        $user_login = $user->get( 'user_email' );
    }
     
    return $user_login;
     
}
